## Convolutioanl Neural Network 

In [2]:
import numpy as np
w = np.array([2, 1, 5, 3])
x = np.array([2, 8, 3, 7, 1, 2, 0, 4, 5])

In [3]:
w_r = np.flip(w)
print(w_r)

# w_r = w[::-1]

[3 5 1 2]


In [4]:
for i in range(6):
    print(np.dot(x[i:i+4], w_r))

63
48
49
28
21
20


In [5]:
# Using scipy for convolution
# valid padding
from scipy.signal import convolve
convolve(x, w, mode='valid')

array([63, 48, 49, 28, 21, 20])

In [6]:
# Cross-Correlation (C-C is usually used doing CNN b/c weights would be randomized. no need to reverse w)

# valid padding 
from scipy.signal import correlate
correlate(x, w, mode='valid')

array([48, 57, 24, 25, 16, 39])

In [7]:
# full padding
correlate(x, w, mode='full')

array([ 6, 34, 51, 48, 57, 24, 25, 16, 39, 29, 13, 10])

In [8]:
# same padding (mostly used when doing CNN)
correlate(x, w, mode='same')

array([34, 51, 48, 57, 24, 25, 16, 39, 29])

In [9]:
# 2D striding

x = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])
w = np.array([[2, 0], [0, 0]])

from scipy.signal import correlate2d
correlate2d(x, w, mode='valid')

array([[ 2,  4],
       [ 8, 10]])

In [10]:
correlate2d(x, w, mode='same')

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [11]:
# Using TensorFlow

import tensorflow as tf
x_4d = x.astype(np.float).reshape(1, 3, 3, 1)
w_4d = w.reshape(2, 2, 1, 1)

In [12]:
c_out = tf.nn.conv2d(x_4d, w_4d, strides=1, padding='SAME') #4d
print(c_out)

tf.Tensor(
[[[[ 2.]
   [ 4.]
   [ 6.]]

  [[ 8.]
   [10.]
   [12.]]

  [[14.]
   [16.]
   [18.]]]], shape=(1, 3, 3, 1), dtype=float64)


In [13]:
c_out.numpy().reshape(3, 3) # 4d -> 2d 

array([[ 2.,  4.,  6.],
       [ 8., 10., 12.],
       [14., 16., 18.]])

In [14]:
# Pooling 

x = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12],
              [13, 14, 15, 16]])

x = x.reshape(1, 4, 4, 1)

In [15]:
x

array([[[[ 1],
         [ 2],
         [ 3],
         [ 4]],

        [[ 5],
         [ 6],
         [ 7],
         [ 8]],

        [[ 9],
         [10],
         [11],
         [12]],

        [[13],
         [14],
         [15],
         [16]]]])

In [16]:
p_out = tf.nn.max_pool2d(x, ksize=2, strides=2, padding='VALID')
p_out.numpy().reshape(2, 2)

array([[ 6.,  8.],
       [14., 16.]], dtype=float32)

In [17]:
# ReLu

def relu(x):
    return np.maximum(x, 0)

In [19]:
x = np.array([-1, 2, -3, 4, -5])
relu(x)

array([0, 2, 0, 4, 0])

In [20]:
# ReLu from tensorFlow

r_out = tf.nn.relu(x) # output type tensor object
r_out.numpy() # change to np

array([0, 2, 0, 4, 0])